FROM node:20-bookworm-slim AS dependencies
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

FROM node:20-bookworm-slim AS builder
WORKDIR /app
COPY --from=dependencies /app/node_modules ./node_modules
COPY . .
ARG NEXT_PUBLIC_API_BASE_URL
ARG NEXT_PUBLIC_CKB_NETWORK
ARG NEXT_PUBLIC_JOYID_APP_URL
ARG NEXT_PUBLIC_JOYID_SERVER_URL
ARG NEXT_PUBLIC_JOYID_AGGREGATOR_URL
ARG NEXT_PUBLIC_CKB_RPC_URL
ARG NEXT_PUBLIC_CKB_EXPLORER_URL
ENV NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL
ENV NEXT_PUBLIC_CKB_NETWORK=$NEXT_PUBLIC_CKB_NETWORK
ENV NEXT_PUBLIC_JOYID_APP_URL=$NEXT_PUBLIC_JOYID_APP_URL
ENV NEXT_PUBLIC_JOYID_SERVER_URL=$NEXT_PUBLIC_JOYID_SERVER_URL
ENV NEXT_PUBLIC_JOYID_AGGREGATOR_URL=$NEXT_PUBLIC_JOYID_AGGREGATOR_URL
ENV NEXT_PUBLIC_CKB_RPC_URL=$NEXT_PUBLIC_CKB_RPC_URL
ENV NEXT_PUBLIC_CKB_EXPLORER_URL=$NEXT_PUBLIC_CKB_EXPLORER_URL
RUN npm run build

FROM node:20-bookworm-slim AS runtime
WORKDIR /app
ENV NODE_ENV=production
ENV HOSTNAME=0.0.0.0
COPY --from=builder /app/package.json /app/package-lock.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
EXPOSE 3000
CMD ["npm", "run", "start"]
