import { test, expect } from "@playwright/test";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { command, LivePilot } from "./live-pilot";

test("pairs a real node, preserves setup, and guides a real signed quote", async ({ page, baseURL }, testInfo) => {
  test.skip(!process.env.LIQUIDLANE_LIVE_RECEIVER_CONFIG || !process.env.LIQUIDLANE_LIVE_PROVIDER_CONFIG, "Requires two running, funded Fiber 0.9.0 testnet nodes and built Core binaries.");
  test.setTimeout(180_000);
  const pilot = new LivePilot();
  try {
    await pilot.start(new URL(baseURL!).origin);
    await pilot.attach(page);
    const errors: string[] = [];
    page.on("pageerror", error => errors.push(error.message));
    await page.goto("/");
    await page.getByRole("button", { name: "Continue as a merchant" }).click();
    await page.getByRole("button", { name: "Request a quote", exact: true }).click();
    const quote = page.getByRole("region", { name: "Request capacity" });
    await expect(quote.getByRole("heading", { name: "Pair a receiving node to continue" })).toBeVisible();
    await expect(quote.getByRole("button", { name: "Request signed quote" })).toHaveCount(0);
    await quote.getByRole("button", { name: "Pair receiving node" }).click();
    await expect(page.getByLabel("Node label", { exact: true })).toHaveValue("My receiving node");
    await expect(page.getByText("A name you choose so you can recognize this node.", { exact: false })).toBeVisible();
    await page.getByLabel("Node label", { exact: true }).fill("Live browser receiver");
    await page.getByRole("button", { name: "Create pairing code", exact: true }).click();
    const setup = page.getByRole("region", { name: "Node pairing progress" });
    await expect(setup.getByText("Action needed · Run connector", { exact: true })).toBeVisible();
    await expect(page.getByLabel("Maximum funding per order · CKB")).toHaveCount(0);
    await expect(page.getByLabel("Node’s full TCP /p2p/ address")).toHaveCount(0);
    const folder = join(pilot.directory, "receiver");
    await mkdir(folder, { mode: 0o700 });
    const downloadEvent = page.waitForEvent("download");
    await setup.getByRole("button", { name: "Download pairing file", exact: true }).click();
    const download = await downloadEvent;
    expect(download.suggestedFilename()).toBe("liquidlane-pairing.json");
    const pairingPath = join(folder, download.suggestedFilename());
    await download.saveAs(pairingPath);
    const pairing = JSON.parse(await readFile(pairingPath, "utf8"));
    expect(pairing.role).toBe("merchant");
    expect(pairing.provider_policy).toBeNull();
    expect(pairing.pairing_code).toMatch(/^[0-9a-f]{64}$/);
    // The compiled app's URL is proxied for the isolated pilot; direct the local CLI to that same API.
    pairing.core_url = pilot.coreURL;
    await writeFile(pairingPath, JSON.stringify(pairing), { mode: 0o600 });
    await page.getByRole("button", { name: "My requests", exact: true }).click();
    await page.getByRole("button", { name: "Supply Liquidity", exact: true }).click();
    await expect(page.getByLabel("Node label", { exact: true })).toHaveValue("My provider node");
    await expect(setup).toHaveCount(0);
    await page.getByRole("button", { name: "Request Capacity", exact: true }).click();
    await page.getByRole("button", { name: "My receiving nodes", exact: true }).click();
    await expect(setup.getByRole("heading", { name: "Live browser receiver" })).toBeVisible();
    await page.reload();
    await expect(setup.getByText("Action needed · Run connector", { exact: true })).toBeVisible();
    await expect(setup.getByRole("heading", { name: "Your node is ready", exact: true })).toHaveCount(0);
    const args = ["setup", pairingPath, "--once"];
    await expect(command(pilot.bin("liquidlane-connector"), args, folder, `${pilot.receiver.fiber_rpc}\n${dirname(dirname(pilot.provider.node_key_file))}\n\n`)).rejects.toThrow("different node than the RPC URL");
    const output = await command(pilot.bin("liquidlane-connector"), args, folder, `${pilot.receiver.fiber_rpc}\n${dirname(dirname(pilot.receiver.node_key_file))}\n\n`);
    expect(output).toContain("Paired merchant node");
    const config = JSON.parse(await readFile(join(folder, "connector.json"), "utf8"));
    expect(config.node_key_file).toBe(pilot.receiver.node_key_file);
    expect(config.fiber_rpc).toBe(pilot.receiver.fiber_rpc);
    expect(config.node_address).toMatch(/\/tcp\/\d+\/p2p\//);
    await expect(setup.getByRole("heading", { name: "Your node is ready", exact: true })).toBeVisible({ timeout: 30_000 });
    await expect(page.getByRole("article", { name: "Live browser receiver node", exact: true })).toBeVisible();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await page.screenshot({ path: testInfo.outputPath("paired-node.png"), fullPage: true });
    await setup.getByRole("button", { name: "Continue to find capacity" }).click();
    await page.getByRole("button", { name: "Request a quote", exact: true }).click();
    await expect(page.getByRole("combobox", { name: "Your receiving node", exact: true })).toContainText("Live browser receiver");
    await expect(page.getByRole("button", { name: "Request signed quote", exact: true })).toBeEnabled();
    await page.getByRole("button", { name: "Request signed quote", exact: true }).click();
    await expect(page.getByRole("heading", { name: "Waiting for the provider’s signature", exact: true })).toBeVisible();
    await command(pilot.bin("liquidlane-connector"), ["run", pilot.providerConfig, "--once"], pilot.directory);
    await expect(page.getByRole("heading", { name: "Your turn: review and accept the quote", exact: true })).toBeVisible({ timeout: 20_000 });
    await expect(page.getByRole("button", { name: "Verify & accept quote", exact: true })).toBeEnabled();
    await expect(page.getByText("You · Merchant", { exact: true })).toBeVisible();
    await expect(page.locator('.order-parties [data-party="provider"]')).toContainText("Live test provider");
    await page.screenshot({ path: testInfo.outputPath("signed-quote.png"), fullPage: true });
    const dashboard = await pilot.api<{ orders: { id: string }[] }>("/market/dashboard", pilot.receiverAccount.session.token);
    expect(dashboard.orders).toHaveLength(1);
    await command(pilot.bin("liquidlane-wallet"), ["approve", pilot.receiverAccount.key, pilot.coreURL, pilot.receiverAccount.sessionFile, dashboard.orders[0].id], pilot.directory);
    await expect(page.getByRole("heading", { name: "Connecting your receiving node automatically", exact: true })).toBeVisible({ timeout: 20_000 });
    await expect(page.getByRole("button", { name: "Copy order ID", exact: true })).toBeVisible();
    await expect(page.getByRole("button", { name: "Pay 61 CKB fee", exact: true })).toHaveCount(0);
    const providerPage = await page.context().newPage();
    await pilot.attach(providerPage, "provider");
    await providerPage.goto("/#lp");
    await expect(providerPage.getByRole("heading", { name: "Publish a capacity offer" })).toBeVisible();
    await expect(providerPage.getByRole("article", { name: "Live browser receiver node" })).toHaveCount(0);
    await expect(providerPage.getByRole("article", { name: "Live test provider node" })).toBeVisible();
    const capital = providerPage.getByRole("region", { name: "Capital for Live test provider" });
    await expect(capital.getByRole("heading", { name: "Fund your node" })).toBeVisible();
    const providerDashboard = await pilot.api<{ nodes: { id: string; funding: { address: string }; available_ckb: number }[] }>("/market/dashboard", pilot.providerAccount.session.token);
    const fundingNode = providerDashboard.nodes[0];
    await expect(capital.getByLabel("Node’s CKB funding address")).toHaveValue(fundingNode.funding.address);
    await expect(capital.locator(".capital-balance strong")).toHaveText(`${fundingNode.available_ckb.toLocaleString()} CKB`);
    await expect(capital.getByRole("button", { name: "Add 61 CKB to my node", exact: true })).toBeEnabled();
    await expect(providerPage.getByRole("list", { name: "Liquidity provider progress" })).toContainText("Add CKB");
    expect(await providerPage.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await providerPage.screenshot({ path: testInfo.outputPath("provider-offers.png"), fullPage: true });
    await providerPage.getByRole("button", { name: "Merchant requests", exact: true }).click();
    await expect(providerPage.getByRole("heading", { name: "Your connector is opening the channel automatically", exact: true })).toBeVisible();
    await expect(providerPage.locator("code").filter({ hasText: "liquidlane-connector approve" })).toHaveCount(0);
    await expect(providerPage.getByText("You · Liquidity provider", { exact: true })).toBeVisible();
    await expect(providerPage.getByRole("button", { name: "Verify & accept quote" })).toHaveCount(0);
    await expect(providerPage.getByRole("button", { name: "Cancel before opening" })).toHaveCount(0);
    expect(await providerPage.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await providerPage.screenshot({ path: testInfo.outputPath("provider-request.png"), fullPage: true });
    await providerPage.getByRole("button", { name: "My offers & nodes", exact: true }).click();
    await providerPage.getByRole("button", { name: "Pair another node", exact: true }).click();
    await providerPage.getByRole("button", { name: "Connect provider node", exact: true }).click();
    await expect(providerPage.getByText("Automatic channel funding", { exact: true })).toBeVisible();
    await expect(providerPage.getByLabel("Allowed merchant wallet addresses")).toHaveCount(0);
    await expect(providerPage.getByLabel("Node setup", { exact: true })).toHaveValue("new");
    await expect(providerPage.locator(".connector-command pre")).toContainText("--new-node --background");
    await providerPage.getByLabel("Node setup", { exact: true }).selectOption("existing");
    await expect(providerPage.locator(".connector-command pre")).toHaveText("liquidlane-connector setup ./liquidlane-pairing.json --background");
    await providerPage.getByLabel("Node setup", { exact: true }).selectOption("new");
    const providerDownloadEvent = providerPage.waitForEvent("download");
    await providerPage.getByRole("button", { name: "Download connector settings", exact: true }).click();
    const providerPath = join(pilot.directory, "public-provider-pairing.json");
    await (await providerDownloadEvent).saveAs(providerPath);
    const providerPairing = JSON.parse(await readFile(providerPath, "utf8"));
    expect(providerPairing.provider_policy).toEqual({ max_order_ckb: 2000, max_total_ckb: 5000, min_fee_ckb: 61, allowed_merchants: [], accept_public_orders: true, auto_approve: true });
    await providerPage.screenshot({ path: testInfo.outputPath("automatic-provider-setup.png"), fullPage: true });
    await providerPage.close();
    await page.getByRole("button", { name: "Find a provider", exact: true }).click();
    await page.getByRole("button", { name: "Continue existing order", exact: false }).click();
    await page.getByRole("button", { name: "Cancel before opening", exact: true }).click();
    await expect(page.getByRole("heading", { name: "This order was cancelled", exact: true })).toBeVisible();
    await expect(page.getByRole("button", { name: "Find capacity again", exact: true })).toBeVisible();
    expect(errors).toEqual([]);
  } finally { await pilot.close(); }
});
