import { ckb } from "./api";
import type { Order } from "./types";

export function OrderProgress({ order, merchant, paymentSaved, expired }: { order: Order; merchant: boolean; paymentSaved: boolean; expired: boolean }) {
  const settled = ["paid", "waived"].includes(order.fee_status);
  let step = 0, title = merchant ? "Waiting for the provider’s signature" : "Your connector is preparing the quote", detail = merchant ? "The provider’s connector checks this request and signs the quote. No payment is due." : order.automatic ? "Your connector signs eligible quotes and automatically funds channels after merchant acceptance, within your budget." : "Keep your provider connector running. It checks your local policy and signs eligible quotes. Funding needs your approval after the merchant accepts.";
  if (order.status === "quoted") { step = 1; title = merchant ? "Your turn: review and accept the quote" : "Waiting for the merchant to accept"; detail = merchant ? `Check the capacity, node reserve, and opening fee below. Select Verify & accept quote and confirm in your wallet. ${order.automatic ? "Acceptance starts automatic channel funding. Your opening fee is due after verified delivery." : "This step makes no fee payment."}` : order.automatic ? "The channel opens automatically after the merchant accepts, within your funding limits. Keep your connector running." : "The merchant must sign the accepted quote before you can approve funding."; }
  if (order.status === "accepted") { step = 2; title = merchant ? "Waiting for the provider’s local approval" : "Your turn: approve on your node machine"; detail = merchant ? "The provider operator must approve this order on their node. Share the order ID if you are coordinating a test. This page updates automatically; no fee is due." : "Review the accepted quote and use your connector’s approve command with this order ID. Keep the connector running."; }
  if (order.status === "accepted" && order.automatic) { title = merchant ? "Connecting your receiving node automatically" : "Your connector is opening the channel automatically"; detail = "The provider’s connector checks the signed quote, available funds, and budget, then connects both nodes and funds the channel. Keep both connectors running. No operator approval or opening fee payment is needed at this step."; }
  if (["opening", "awaiting_confirmation"].includes(order.status)) { step = 2; title = "Channel opening is in progress"; detail = "Keep both nodes and connectors running. Waiting for confirmed funding and matching channel reports. No fee is due yet."; }
  if (order.status === "verifying") {
    step = order.probe_received ? 4 : 3;
    title = order.probe_received ? merchant ? "Your turn: verify delivered capacity" : "Waiting for the merchant to verify delivery" : order.probe_invoice ? "Next: receive a 1 CKB test payment" : "Preparing the test payment invoice";
    detail = order.probe_received ? merchant ? "Your node reports the test payment as Paid. Verify delivery to check confirmed funding and the agreed receiving capacity." : "The merchant’s node reports the test payment as Paid. The merchant can now verify delivery." : order.probe_invoice ? "Copy the invoice below and give it to a separate Fiber payer with a route through the provider. The payer sends 1 testnet CKB; this is separate from the opening fee." : "The merchant’s connector creates the invoice after it sees the channel. Keep both connectors running; this page updates automatically.";
  }
  if (order.status === "delivered") { step = settled ? 6 : 5; title = settled ? "Complete: delivery verified and fee settled" : merchant ? paymentSaved ? "Your payment is saved: checking confirmation" : `Your turn: pay the ${ckb(order.quote.opening_fee_ckb)} CKB opening fee` : "Waiting for the opening fee"; detail = settled ? "Export your signed receipt below. Channel state and current receiving capacity are tracked separately." : paymentSaved ? "LiquidLane checks confirmation automatically. You can also use Check confirmation. If submission needs a retry, resubmit the saved payment without signing a new one." : "Delivery is verified. The merchant pays the provider directly from their browser wallet, plus the CKB transaction fee. A receipt is available below."; }
  const terminal = ["cancelled", "expired", "failed"].includes(order.status) || expired;
  if (terminal) { title = expired || order.status === "expired" ? "This quote expired" : order.status === "cancelled" ? "This order was cancelled" : "This order could not open"; detail = merchant ? "No opening fee is due. Return to Find a provider to request a new quote." : "No opening fee is due. The merchant can request a new quote from your published offer."; }
  if (order.status === "reconciling") { step = 2; title = "Provider action needed: check the opening"; detail = "Funding may have started. The provider must inspect the existing channel and funding transaction before taking further action. No opening fee is due."; }
  const labels = ["Quote", "Accept", "Open channel", "Test payment", "Verify delivery", "Pay fee"];
  return <div className="order-progress">
    <ol className="order-steps" aria-label="Order progress">{labels.map((label, i) => <li key={label} className={i < step ? "done" : i === step && !terminal ? "current" : ""} aria-current={i === step && !terminal ? "step" : undefined}><span>{i < step ? "✓" : i + 1}</span>{label}</li>)}</ol>
    <div className="notice" role="status"><h4>{title}</h4><p>{detail}</p></div>
  </div>;
}
